[tool.poetry]
name = "ash-random-quote-generator"
version = "0.1.0"
description = ""
authors = ["Ash_Crow <sylvain@ashtree.eu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
